// Generated by CoffeeScript 1.7.1
(function(window, document) {
  var cursor, headline, item, linkItems, _i, _len;
  headline = document.getElementById('headline');
  cursor = document.getElementById('cursor');
  linkItems = document.getElementsByClassName('link-item');
  for (_i = 0, _len = linkItems.length; _i < _len; _i++) {
    item = linkItems[_i];
    item.onmouseover = function(e) {
      var href, _ref, _ref1, _ref2;
      if (((_ref = e.target) != null ? _ref.className : void 0) !== 'link-item') {
        return;
      }
      if (!(href = (_ref1 = e.target.getElementsByTagName('a')) != null ? (_ref2 = _ref1[0]) != null ? _ref2.href : void 0 : void 0)) {
        return;
      }
      headline.innerHTML = href;
      cursor.classList.remove('hidden');
      return cursor.classList.add('blink');
    };
    item.onmouseout = function(e) {
      var toEl;
      toEl = e.toElement;
      while (toEl != null ? toEl.parentNode : void 0) {
        if (toEl.className === 'link-item') {
          return;
        }
        toEl = toEl.parentNode;
      }
      headline.innerHTML = 'Internet Enthusiast';
      cursor.classList.add('hidden');
      return cursor.classList.remove('blink');
    };
    continue;
  }
})(this, this.document);
